name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [<<node-version>>, latest]

    steps:
    
    - name: Checkout branch ${{ github.head_ref || github.ref_name }} 
      uses: actions/checkout@v4

    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # CI tests should install unpinned dependencies
    #  - from: OSSF: Package Manager Best Practices
    - name: Install unpinned dependencies
      run: npm install --no-package-lock
      
    - name: Run tests
      run: node --run test
      env:
        NODE_ENV: test
