name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      NODE_ENV: test
    strategy:
      matrix:
        node-version: [<<node-version>>, latest]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    # CI tests should install unpinned dependencies
    #  - from: OSSF: Package Manager Best Practices: npm
    - run: npm install --no-package-lock
    - run: node --run test
