name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      NODE_ENV: test
    strategy:
      matrix:
        node-version: [<<node-version>>, latest]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    # From OSSF: Package Manager Best Practices  
    # Read: https://tinyurl.com/bdf3yuvv
    - run: npm i --no-package-lock

    - run: node --run test
